### PR TITLE
Fix typos

### LINKED ISSUE #654: typo fixes
**Describe the bug**
There are typos in the code.

- rename optionnal_maybe to optional_maybe
- other typos like as "informations"

I will open a PR shortly.

### PR DESCRIPTION
**Pull request by chunghha**
To fix #654 please review.

### CODE REVIEW

**Comment by rrousselGit** [comment]
Thanks! This seems to break a JSON test though. Could you fix it? :pray:

**Comment by chunghha** [comment]
I am not familiar with the regression testing. Just replacing "isFalse" at the line 29/33 to "isTrue" is good enough?

**Comment by rrousselGit** [comment]
No. The behaviour should stay the same

You need to modify json_test to match the naming change

**Comment by chunghha** [comment]
Then, just rollback this change? 
Screen Shot 2022-04-25 at 1 30 43 AM

**Comment by chunghha** [comment]
I just rollbacked the "regresssion" typo fix in the test instead of fixing what I don't understand fully.

**Comment by rrousselGit** [comment]
Actually you may have spotted an incorrect test. I'll fix it separately.

Thanks for your PR! 😄

**Pull request merged**
