### PR TITLE
Removes union key from json to be deserialized

### PR DESCRIPTION
**Pull request by Nolence**
This addresses #226

I know changes usually require tests but I'm not sure how one could be added. Adding the disallow_unrecognized_keys is in a way enforcing a stricter interface. All Current tests do pass though.

Lemme know

### CODE REVIEW

**Comment by rrousselGit** [comment]
Mutating the `json` is not a good idea. This could have unexpected results
Instead consider making a clone

Could you also add a test for this?

**Comment by Nolence** [comment]
I copied every test that involved a unionkey and added annotation specific to jsonserializable.

Added a map copy as well. You're right that this copy is probably less performant but I don't see that many people using the sealed unions to deserialize data anyways. Another option would be to grab the annotation for JsonSerializable and do a check to see if it has the unrecognizedKeys set and then do conditional logic from there

**Comment by rrousselGit** [comment]
What do you think about generating a property with the matching name instead?

Such that we have:

```dart
@JsonSerializable()
class Example {
  @JsonKey()
  final String type;
}
```


This may require changing the default key from `runtimeType` to `type`, which is breaking.
But that's probably a good change anyway

What do you think?

**Comment by Nolence** [comment]
That's a cool idea. Would that require people change their database though or would you be able to

```dart
@JsonSerializable()
class Example {
  @JsonKey(name: 'runtimeType')
  final String type;
}
```
?

Also, instead of string, what about an enum? Not sure of the value of it, but I think it'd possibly be good. We could then generate every enum possibility which would solve #434.

**Comment by rrousselGit** [comment]
> or would you be able to
> 
> ```dart
> @JsonSerializable()
> class Example {
>   @JsonKey(name: 'runtimeType')
>   final String type;
> }
> ```
> 
> ?

I think that would work. But it needs to be tested

We could generate an enum, but I'm not sure if that's worth the trouble. Ultimately for https://github.com/rrousselGit/freezed/issues/74 there's a lot more work to be done than this

**Comment by Nolence** [comment]
> We could generate an enum, but I'm not sure if that's worth the trouble.

No worries, just a random thought I had. Yeah, I'll test out adding that field `type` and wiring things up this weekend and update you with any progress/questions I have

**Comment by rrousselGit** [comment]
Awesome thanks a lot, and sorry for the slow review

**Comment by rrousselGit** [comment]
Hello!

As a comeback to this, what is the reasoning for still removing `type`? Did the `@JsonKey` on a `type` failed to produce the expected result?

**Pull request merged**
