### PR TITLE
fix: use nullable return type in *OrNull callbacks

### LINKED ISSUE #741: mapOrNull callback return type is non-null
Currently the generated `mapOrNull` / `whenOrNull` callbacks specify a non-null return type.

```dart
@optionalTypeArgs
TResult? mapOrNull<TResult extends Object?>({
  TResult Function(A value)? a,
  TResult Function(B value)? b,
})
```

This forces us to write something like
```dart
value.mapOrNull<int?>(a: (v) => v.abc));
```
when we access a nullable property.

### PR DESCRIPTION
**Pull request by DevNico**
closes #741

### CODE REVIEW

**Comment by rrousselGit** [comment]
Hello!

Sorry for the delay. Could you write tests for this?

**Comment by DevNico** [comment]
Will do next week!

**Comment by DevNico** [comment]
Done :)

**Comment by rrousselGit** [comment]
Thanks a lot!

**Pull request merged**
