### PR TITLE
Extension of the changes made in 1.1.1 #514

### PR DESCRIPTION
**Pull request by smiLLe**

### CODE REVIEW

**Comment by rrousselGit** [comment]
Hello!

What is this about?
Also, could you add some tests for it?

**Comment by smiLLe** [comment]
You made a change here https://github.com/rrousselGit/freezed/commit/56b4fb7095f1b8273412b452725f80a8317d9394
But it did not solve the issue mentioned here #514
Instead this PR will fixed #514

**Comment by smiLLe** [comment]
I am not exactly sure how to write a test for this case :(

**Comment by rrousselGit** [comment]
LGTM

**Pull request merged**
