### PR TITLE
fix: allow dollar ($) in recursive class names

### LINKED ISSUE #898: Recursive classes with dollar ($) are not parsed correctly
**Describe the bug**
When using classes that haven't been generated yet, freezed doesn't parse the class name correctly **if it has a dollar**.

**To Reproduce**

```
@freezed
class RecursiveWith$Dollar with _$RecursiveWith$Dollar {
  factory RecursiveWith$Dollar() = RecursiveWith$DollarImpl;
  factory RecursiveWith$Dollar.next(RecursiveWith$DollarImpl value) =
      _RecursiveWith$DollarNext;
}
```

This generates `DollarImpl value` instead of `RecursiveWith$DollarImpl value`.

**Root cause**

This regex doesn't include $.

https://github.com/rrousselGit/freezed/blob/51d2fab36c338180d74f3214e3446ad3bc88a84f/packages/freezed/lib/src/templates/concrete_template.dart#L568

A PR is coming in a few minutes.

### PR DESCRIPTION
**Pull request by andreasgangso**
fixes #898

### CODE REVIEW

**Comment by rrousselGit** [comment]
LGTM. Will merge/publish a bit later.

If I forget, please ping me~

**Comment by andreasgan** [comment]
don't know what you meant by later, so pinging you now @rrousselGit

**Comment by andreasgan** [comment]
I'm assuming you forgot @rrousselGit :)

**Comment by rrousselGit** [comment]
LGTM!

**Pull request merged**
