### PR TITLE
Add option `fromJsonFactory` and `toJson` to toogle code generations

### PR DESCRIPTION
**Pull request by morlay**
fix https://github.com/rrousselGit/freezed/issues/451

### CODE REVIEW

**Comment by rrousselGit** [comment]
I do not want to make Freezed dependent on how json_serializable works.

If we're going to disable the fromJson generation, this should be parameterized using Freezed options instead of json_serializable options

**Comment by morlay** [comment]
@rrousselGit Yes. 

But in fact, Freezed depend `fromJson` which generated by `json_serializable`;
When `@JsonSerializable(createFactory: false)`, Freezed will generate wrong codes with unknown "xxxFromJSON" function.

For `toJson`, could be disabled by another way. 
When custom `toJson` defined,  don't generate it.

**Comment by rrousselGit** [comment]
Right, because disabling the generation of the factory is not supported.

If we want to support this, it shouldn't be through `@JsonSerializable(createFactory: false)` but a Freezed annotation instead.

**Comment by morlay** [comment]
@rrousselGit

But in that way, it will change a lot.
need consider merge `createFromJson` and `createToJson` of `Freezed` into `JsonSerializable`.
Configurate twice is terrible.

**Comment by morlay** [comment]
@rrousselGit  if we decide to add options of `Freezed`.

How about `@freezed(createFromJsonFactory: false, createToJson: false)` ?

I will try to refact this PR to got it.

**Comment by rrousselGit** [comment]
By default, users do not specify the `@JsonSerializable` annotation.

So when we do `@Freezed(fromJson: false)`, then the generator can generate `@JsonSerializable(createFactory: false)`

**Comment by morlay** [comment]
@rrousselGit updated. 

Follow the option styles, now it will be:
`@Freezed(fromJsonFactory: false, toJson: false)`
it could disable only one of  `fromJsonFactory` or `toJson` like `@JsonSerializable` did.

**Comment by morlay** [comment]
Hi @rrousselGit
is there other concerns?

**Comment by yh-luo** [comment]
This implementation is really useful for creating data models from API responses. Currently, I need to either manually remove all `toJson` in `*.freezed.dart`, or give up on `create_to_json: false`.
Would this PR be merged?

Or maybe `freezed` is not suitable for that use case? (but I really like the ==/toString implementations)

**Comment by sadi304** [comment]
This is getting merged? useful for the coverage as some apis are only get only

**Comment by rrousselGit** [comment]
Closing as I'll take care of this in a different PR

I'll revamp this to allow disabling _anything_ instead of only fromJson/toJson

Your work is very appreciated though :smile:

**Pull request closed without merging**
