### PR TITLE
DiagnosticableTreeMixin related code still generated when foundation.dart is not imported

### PR DESCRIPTION
**Pull request by avbk**
Hey Remi,

first of all thanks for this awesome library :tada: 

I wanted to get a deeper understanding of the internals of freezed and thus I considered to fix a bug or two... So I picked #220, which you labeled as a good starting point. _(honestly, it was trickier than I expected it to be in the first place)_

The problem with the current implementation is that `_libraryHasElement` searches recursively for any exported classes within the imports, but it does not take the `show` and `hide` keyword into account. 
I moved `_libraryHasElement` into a separate class `RecursiveImportLocator` and added some logic to consider `show` and `hide`. It's quite a simple approach and I might have overlooked some edge case, but at least for the described issue it works :wink: 

I hope this PR is fine for you and I'm curious about your feedback :slightly_smiling_face: 

Best regards,
Alex

@skybur @rrousselGit

### CODE REVIEW

**Comment by avbk** [comment]
Sadly the decorator tests fail on travis eventhough they work on my machine... 
And I actually don't expect any regression in this part of freezed. Do you have a clue about what might be wrong?

**Comment by rrousselGit** [comment]
It was a bug due to the CI using a different version of a dependency
If you pull from master, that should fix it

**Comment by avbk** [comment]
Awesome, will take care of this tomorrow

**Comment by avbk** [comment]
... and done :slightly_smiling_face:

**Comment by rrousselGit** [comment]
Nice thanks a lot!

**Comment by avbk** [comment]
Sure thing :slightly_smiling_face:

**Pull request merged**
