### PR TITLE
Use regex to parse With and Implements annotations

### PR DESCRIPTION
**Pull request by sroddy**
I propose a different way for parsing and outputting the `@With` and `@Implements` annotations that use the new "generic" approach.
The rationale is that we should be able to assume that the soundness (syntax error and well-formed types within the generic quotes) is guaranteed by the compiler itself, and whichever type is extracted by the regex can be copy-pasted, as it is, inside the generated file.

This approach would also solve edge-case situations like the one that surfaced in #535

### CODE REVIEW

**Comment by rrousselGit** [comment]
Using `toSource` instead reliable / anti-pattern. For example folks could do:

```dart
const alias = With<Some<Complex<Type>>>();

@freezed
class Example with _$Example {
  @alias // that should work, but toSource would break this
  factory Example.first() = _ExampleFirst;
}
```

It should be possible to fix the bug mentioned without relying on manually parsing the source.

**Comment by sroddy** [comment]
I think that the limitation that we have now (i.e. not being able to use any generated class inside the @With annotation) is much more painful than not supporting the complex use-case you posted above.

Of course I would love not to rely on a non-reliable implementation, but I'm a bit lost on how I could do that.
Do you have any idea/suggestion about how to do it?

**Comment by rrousselGit** [comment]
The previous code relied on DartObject to obtain the generic type.
Chances are there are some extra informations I didn't use that contains the generics of the generic type used by the annotation

**Comment by sroddy** [comment]
I've tried to play a bit with that when I was implementing this alternative approach and I failed finding an alternative like the one you are suggesting. The problem is that if the generic is tried to be resolved in any way by the analyzer package, and the type is generated by freezed, it gets resolved as `dynamic`. Of course I may be missing something, but it's very hard for me to completely understand how the `analyzer` package really works as its somewhat hard to find docs and examples that uses it in a complex scenario like the freezed one

**Comment by rrousselGit** [comment]
>  The problem is that if the generic is tried to be resolved in any way by the analyzer package, and the type is generated by freezed, it gets resolved as dynamic.

I'm alright with that.

To begin with you shouldn't use a Freezed class inside a `@With`/`@Implements`.

**Comment by sroddy** [comment]
>To begin with you shouldn't use a Freezed class inside a @With/@Implements.

Why? Unfortunately Dart doesn't let you define an interface that contains existential types (for example that contains a method which returns Self/This), so it's pretty common to have interfaces that are generic to the specific instance that implements the interface itself in order to overcome that issue.

https://github.com/dart-lang/sdk/issues/28477

BTW, this was a perfectly supported scenario until v0.15 and I think it's quite a pity that it can no longer be supported.

**Comment by rrousselGit** [comment]
I don't like using regex here. What do you think about adding the `fromString` constructor back? We could have `@WithFromString('MyClass')`

**Comment by rrousselGit** [comment]
:wave:

I don't think I'll go forward with this change. A regex for parsing the source code is IMO dangerous

**Pull request closed without merging**
